### ISSUE TITLE
Нужен пример работы стандартизации (PHONE)

### ISSUE THREAD

**Issue by doksec** [vgrish/dadata#1]
И можно ли как то для одной формы использовать подсказки (free) и стандартизацию (pay) для экономии?
 Можно ли сделать два вызова для одного селектора формы, но с разными параметрами?

Попробовал переключить в pay. Перестали работать подсказки. Думаю это нормально, если этот режим рассчитан на стандартизацию, но нужен пример.

**Comment by vgrish** [comment]
стандартизация в стандартном js не предусмотрена . Нужно писать.
Для работы в pay помоему нужно обратится в поддержку DaData, просто так она не работает.
